import time
print("------------------------------")
print("FUCKING NONSENSE SIMULATOR")
print("OR BITCHES SIMULATOR")
print("NO FUCKING SENSE WARNING")
print("THERES NOT EVEN A GAIN FUNCTION")
print("MADE BY YOUR NEAREST SEX CLUB")
print("------------------------------")
print("bitch getting starts in 5 seconds")
time.sleep(5)
print("you are a peasent, having no bitches at all.")
print("rebirths: 0")
print("mega rebirths: 0")
print("giga rebirths: 0")
time.sleep(1)
print("you have 1 bitch")
time.sleep(1)
print("you have 2 bitches")
time.sleep(1)
print("you have 4 bitches")
time.sleep(1)
print("you have 8 bitches")
time.sleep(1)
print("you have 16 bitches")
print("NEW UPGRADE UNLOCKED! Cock Sucker 3000")
time.sleep(1)
print("you have 52 bitches")
print("EXTRA 20 BITCHES GOTTEN! reason: Cock Sucker 3000, Now disabling.")
time.sleep(1)
print("you have 80 bitches")
time.sleep(1)
print("you have 100 bitches")
print("GOAL #1 PASSED!")
time.sleep(1)
print("you have 150 bitches")
print("NEW UPGRADE UNLOCKED! Cummer 9000")
time.sleep(1)
print("you have 300 bitches")
print("EXTRA 50 BITCHES GOTTEN! reason: Cummer 9000, Now disabling.")
time.sleep(1)
print("you have 500 bitches")
print("HALFWAY GOAL #2!")
time.sleep(1)
print("you have 750 bitches")
time.sleep(1)
print("you have 1000 bitches")
print("GOAL #2 PASSED!")
time.sleep(1)
print("you have 2500 bitches")
print("NEW UPGRADE UNLOCKED! Website Creator 9000")
time.sleep(1)
print("you have 5500 bitches")
print("EXTRA 500 BITCHES GOTTEN! reason: Website Creator 9000, Now disabling.")
time.sleep(1)
print("you have 8000 bitches")
time.sleep(1)
print("you have 10000 bitches")
print("GOAL #3 PASSED!")
time.sleep(2)
print("you have 20000 bitches")
time.sleep(2)
print("you have 50000 bitches")
print("NEW UPGRADE UNLOCKED! Dick Killer 69420")
time.sleep(2)
print("you have 75000 bitches")
print("EXTRA 5000 BITCHES GOTTEN! reason: Dick Killer 69420, Now disabling.")
time.sleep(2)
print("you have 100k bitches")
print("GOAL #4 PASSED! extreme numbers warning")
time.sleep(2)
print("you have 150k bitches")
time.sleep(2)
print("you have 250k bitches")
print("NEW UPGRADE UNLOCKED! The Entire Fucking Moon")
time.sleep(2)
print("you have 450k bitches")
print("NO BITCHES GOTTEN NORMALLY, BUT EXTRA 200K BITCHES GOTTEN! reason: The Entire Fucking Moon, Now disabling.")
time.sleep(2)
print("you have 500k bitches")
time.sleep(2)
print("you have 750k bitches")
time.sleep(2)
print("you have 1m bitches")
print("GOAL #5 UNLOCKED! so much numbers you got there")
time.sleep(2)
print("you have 2.5m bitches")
print("NEW UPGRADE UNLOCKED! Fucking Golden Moon")
time.sleep(2)
print("you have 5.5m bitches")
print("EXTRA 500K BITCHES GOTTEN! reason: Fucking Golden Moon, Now disabling.")
time.sleep(2)
print("you have 7.5m bitches")
time.sleep(2)
print("you have 10m bitches")
print("GOAL #6 UNLOCKED! good luck kiddo, next goal at 100m bitches instead of 50m")
time.sleep(3)
print("you have 15m bitches")
print("NEW UPGRADE UNLOCKED! Death Star")
time.sleep(3)
print("you have 26m bitches")
print("EXTRA 1M BITCHES GOTTEN! reason: Death Star, Now disabling.")
print("version: update 1 alpha, made by cdh8u")
time.sleep(100)