import time
print("------------------------------")
print("FUCKING NONSENSE SIMULATOR")
print("OR BITCHES SIMULATOR")
print("NO FUCKING SENSE WARNING")
print("THERES NOT EVEN A GAIN FUNCTION")
print("MADE BY YOUR NEAREST SEX CLUB")
print("------------------------------")
print("bitch getting starts in 5 seconds")
time.sleep(5)
print("you are a peasent, having no bitches at all.")
print("rebirths: 0")
print("mega rebirths: 0")
time.sleep(1)
print("you have 1 bitch")
time.sleep(1)
print("you have 2 bitches")
time.sleep(1)
print("you have 4 bitches")
time.sleep(1)
print("you have 8 bitches")
time.sleep(1)
print("you have 16 bitches")
print("NEW UPGRADE UNLOCKED! Cock Sucker 3000")
time.sleep(1)
print("you have 52 bitches")
print("EXTRA 20 BITCHES GOTTEN! reason: Cock Sucker 3000, Now disabling.")
time.sleep(1)
print("you have 80 bitches")
time.sleep(1)
print("you have 100 bitches")
print("GOAL #1 PASSED!")
time.sleep(1)
print("you have 150 bitches")
print("NEW UPGRADE UNLOCKED! Cummer 9000")
time.sleep(1)
print("you have 300 bitches")
print("EXTRA 50 BITCHES GOTTEN! reason: Cummer 9000, Now disabling.")
time.sleep(1)
print("you have 500 bitches")
print("HALFWAY GOAL #2!")
time.sleep(1)
print("you have 750 bitches")
time.sleep(1)
print("you have 1000 bitches")
print("GOAL #2 PASSED!")
time.sleep(1)
print("you have 2500 bitches")
print("NEW UPGRADE UNLOCKED! Website Creator 9000")
time.sleep(1)
print("you have 5500 bitches")
print("EXTRA 500 BITCHES GOTTEN! reason: Website Creator 9000, Now disabling.")
time.sleep(1)
print("you have 8000 bitches")
time.sleep(1)
print("you have 10000 bitches")
print("GOAL #3 PASSED!")
print("the end of game, see you when i get more bitches. made by cdh8u")